spring.datasource.url=jdbc:postgresql://localhost:5432/camunda
spring.datasource.username=camunda
spring.datasource.password=camunda
spring.datasource.driver-class-name=org.postgresql.Driver

# Camunda Properties
camunda.bpm.database.schema-update=true
camunda.bpm.job-execution.enabled=true